project/person/urls.py
from django.urls import path, include
from person.api_views import PersonCreateView, TxtDownloadFileView, XlsxDownloadFileView
from person.views import RequestResultListView, LoginTemplateView

app_name = "person"
urlpatterns = [
    path("api/v1/", include([
        path("useradd/", PersonCreateView.as_view(), name="person-add"),
        path("download-txt/", TxtDownloadFileView.as_view(), name="txt-download"),
        path("download-xlsx/", XlsxDownloadFileView.as_view(), name="xlsx-download"),
    ])),
    path("login/", LoginTemplateView.as_view(), name="person-login"),
    path("results/", RequestResultListView.as_view(), name="request-result-list"),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.views.generic import RedirectView


schema_view = get_schema_view(
   openapi.Info(
      title="Тестовое задание",
      default_version='v1',
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
   path('', RedirectView.as_view(url='/swagger/')),
   path('', include(("person.urls", "person"))),
   path('admin/', admin.site.urls),
   path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/person/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    name = models.CharField(max_length=300)
    birth_date = models.DateTimeField(null=True, blank=True)
    phone = models.CharField(max_length=200, null=True, blank=True)
    email = models.CharField(max_length=200, null=True, blank=True)

    class Meta:
        constraints = [
            models.CheckConstraint(
                name="%(app_label)s_%(class)s_phone_or_email",
                check=(
                    models.Q(phone__isnull=False) 
                    | models.Q(email__isnull=False)
                ),
            )
        ]

    def __str__(self) -> str:
        return self.name

project/person/models/result.py
from django.db import models


class RequestStatus(models.TextChoices):
    """Статусы выполнения задачи."""
    SUCCESS = "success", "Успешно выполнен"
    FAILURE = "failure", "Завершен с ошибкой"


class RequestResult(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(verbose_name="Статус запроса",
                              choices=RequestStatus.choices, max_length=100,
                              default=RequestStatus.SUCCESS, blank=True)
    text = models.TextField(verbose_name="Результат запроса")
    status_code = models.CharField(verbose_name="Статус ответа", max_length=10,
                                   default="0")

    def __str__(self) -> str:
        return str(self.id)

    @property
    def is_successful(self):
        return self.status == RequestStatus.SUCCESS
    
    @property
    def is_failed(self):
        return self.status == RequestStatus.FAILURE

project/person/models/user.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    name = models.CharField(max_length=300)
    birth_date = models.DateTimeField(null=True, blank=True)
    phone = models.CharField(max_length=200, null=True, blank=True)
    email = models.CharField(max_length=200, null=True, blank=True)

    class Meta:
        constraints = [
            models.CheckConstraint(
                name="%(app_label)s_%(class)s_phone_or_email",
                check=(
                    models.Q(phone__isnull=False) 
                    | models.Q(email__isnull=False)
                ),
            )
        ]

    def __str__(self) -> str:
        return self.name

project/person/forms.py
from django import forms
from django.contrib.auth import authenticate


class LoginForm(forms.Form):
    username = forms.CharField(
        widget = forms.TextInput(
            attrs = {
                'placeholder': "Логин"
            }),
        label="Ваш логин",
    )
    password = forms.CharField(
        widget = forms.PasswordInput(
            attrs = {
                'placeholder': 'Пароль'
            }
        ),
        label="Пароль"
    )
    
    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get("username", None)
        password = cleaned_data.get("password", None)
        user = authenticate(username=username,
                            password=password)
        if not user:
            raise forms.ValidationError("Check the entered data")
        return cleaned_data

project/person/views.py
from django.views import generic, View
from django.shortcuts import redirect
from person.models import RequestResult
from person.forms import LoginForm
from django.http import JsonResponse
from rest_framework import status
from django.contrib.auth import login, authenticate
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin


class AnonymousUserMixin(View):
    def render_to_response(self, context, **response_kwargs):
        if self.request.user.is_authenticated:
            return redirect('/')
        return super().render_to_response(context, **response_kwargs)


class LoginTemplateView(AnonymousUserMixin, generic.TemplateView):
    template_name = "person/login.html"
    form = LoginForm
    
    def post(self, request, *args, **kwargs):
        form: LoginForm = self.form(request.POST)
        if not form.is_valid():
            return JsonResponse(form.errors, status=status.HTTP_400_BAD_REQUEST)
        user = authenticate(
            username=form.cleaned_data.get("username", None),
            password=form.cleaned_data.get("password", None)
        )
        login(request, user)
        response = {
            "redirect": reverse_lazy("person:request-result-list")
        }
        return JsonResponse(response, status=status.HTTP_200_OK)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = self.form
        return context


class RequestResultListView(LoginRequiredMixin, generic.ListView):
    model = RequestResult
    queryset = RequestResult.objects.all()
    template_name = "person/response-list.html"
    login_url = '/login/'
    redirect_field_name = 'redirect_to'

project/person/templates/person/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Авторизация{% endblock %}

{% block content %}
    <form method="POST" class="auth-form">
        {% csrf_token %}
        {% for field in form %}
            <div>
                <label for="{{ field.auto_id }}" >{{ field.label }}</label>
                {{ field }}
            </div>
        {% endfor %}
        <input type="submit" value="Авторизоваться">
    </form>
{% endblock %}

{% block extra_scripts %}
    <script type="module" src="{% static '/js/auth.js' %}"></script>
{% endblock %}

project/person/templates/person/response-list.html
{% extends 'base.html' %}
{% load static %}

{% block extra_style %}
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
{% endblock %}

{% block content %}
    <div>
        <a href="{% url 'person:txt-download' %}" class="download-link">Посмотреть отчет в формате .txt</a>
        <a href="{% url 'person:xlsx-download' %}" class="download-link">Посмотреть отчет в формате .xlsx</a>
    </div>
    <table border="1" width="100%" cellpadding="5">
        <tr>
            <th>Порядоковый номер запроса</th>
            <th>Дата отправки запроса</th>
            <th>Статус запроса</th>
            <th>Статус-код ответа от сервера</th>
            <th>Сообщение об ошибке</th>
        </tr>
        {% for result in object_list %}
            <tr>
                <th>{{ result.id }}</th>
                <th>{{ result.date }}</th>
                <th>{{ result.status }}</th>
                <th>{{ result.status_code }}</th>
                <th>{{ result.text }}</th>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Persons{% endblock %}</title>
    {% block extra_style %}{% endblock %}
</head>
<body>
    {% block content %}
        
    {% endblock %}
    {% block extra_scripts %}{% endblock %}
</body>
</html>